version: 0.2

env:
  parameter-store:
    SONAR_LOGIN: "/okky/codebuild/sonar.login"

phases:
  build:
    commands:
      - aws s3 cp s3://config-okky-stg/settings.xml /root/.m2/settings.xml --region=ap-northeast-2
      - mvn clean deploy sonar:sonar -P stg -Dsonar.login=$SONAR_LOGIN

artifacts:
  files:
    - target/okky-share-1.0.1.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'